### PR TITLE
Production Logging 

### PR DESCRIPTION
**Pull request by jatinkatyal13**
- production logging added
- codacy errors fixed

### CODE REVIEW

**Comment by jatinkatyal13** [comment]
Should I add migrations to ignore?

**Comment by aashutoshrathi** [comment]
Yeah that's good.

**Comment by jatinkatyal13** [comment]
I wasn't able to retrieve the recent crash log that's why thought of adding it! May be I was missing out on something!

**Comment by jatinkatyal13** [comment]
That's cool! Then we just need to update the procfile

**Comment by jatinkatyal13** [comment]
Closing this PR

**Pull request closed without merging**
